### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by MehmetYildirimDev** [MehmetYildirimDev/FlappyBird#1]
- [x] Main menu going to added
- [x] Game Over menu going to added
- [x] Audio going to added
